from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.pdfbase.acroform import AcroForm
from reportlab.pdfgen import canvas


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "shadowrun_3e_fillable_character_sheet.pdf"
PAGE_W, PAGE_H = letter
M = 30


def label(c, text, x, y, size=7, bold=False):
    c.setFont("Helvetica-Bold" if bold else "Helvetica", size)
    c.setFillColor(colors.HexColor("#242424"))
    c.drawString(x, y, text)


def section(c, text, x, y, w, h):
    c.setStrokeColor(colors.HexColor("#2b2b2b"))
    c.setLineWidth(0.8)
    c.roundRect(x, y, w, h, 3, stroke=1, fill=0)
    c.setFillColor(colors.HexColor("#2b2b2b"))
    c.rect(x, y + h - 15, w, 15, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(x + 5, y + h - 11, text)
    c.setFillColor(colors.black)


def text_field(c, name, x, y, w, h=13, font_size=8, multiline=False):
    c.acroform.textfieldRelative(
        name=name,
        x=x,
        y=y,
        width=w,
        height=h,
        borderStyle="underlined",
        borderColor=colors.HexColor("#6d6d6d"),
        fillColor=colors.white,
        textColor=colors.black,
        forceBorder=True,
        fontName="Helvetica",
        fontSize=font_size,
        fieldFlags="multiline" if multiline else "",
    )


def checkbox(c, name, x, y, text):
    c.acroform.checkboxRelative(
        name=name,
        x=x,
        y=y,
        size=9,
        borderColor=colors.HexColor("#444444"),
        fillColor=colors.white,
        textColor=colors.black,
        buttonStyle="check",
        forceBorder=True,
    )
    label(c, text, x + 13, y + 1, 7)


def boxed_field(c, name, text, x, y, w, h=13):
    label(c, text, x, y + h + 2, 6.5, True)
    text_field(c, name, x, y, w, h)


def small_grid(c, prefix, items, x, y, field_w=44, row_h=17):
    for i, item in enumerate(items):
        yy = y - i * row_h
        label(c, item, x, yy + 3, 7, True)
        text_field(c, f"{prefix}_{item.lower().replace(' ', '_')}", x + 26, yy, field_w, 12)


def line_table(c, prefix, headers, rows, x, y, widths, row_h=17):
    cx = x
    for head, w in zip(headers, widths):
        label(c, head, cx + 2, y + 3, 6.3, True)
        cx += w
    c.setStrokeColor(colors.HexColor("#999999"))
    c.line(x, y, x + sum(widths), y)
    for r in range(rows):
        yy = y - (r + 1) * row_h
        cx = x
        for idx, w in enumerate(widths):
            text_field(c, f"{prefix}_{r + 1}_{idx + 1}", cx + 1, yy + 2, w - 3, 11)
            cx += w


def condition_monitor(c, prefix, text, x, y, boxes=10):
    label(c, text, x, y + 14, 7, True)
    for i in range(boxes):
        c.acroform.checkboxRelative(
            name=f"{prefix}_{i + 1}",
            x=x + i * 13,
            y=y,
            size=10,
            borderColor=colors.HexColor("#333333"),
            fillColor=colors.white,
            textColor=colors.black,
            buttonStyle="check",
            forceBorder=True,
        )
    label(c, "+1", x + 38, y - 8, 5.5)
    label(c, "+2", x + 77, y - 8, 5.5)
    label(c, "+3", x + 116, y - 8, 5.5)


def build():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(OUT), pagesize=letter)
    c.setTitle("Shadowrun 3rd Edition Fillable Character Sheet")
    c.setAuthor("Generated by Codex")
    c.acroform = AcroForm(c)

    c.setFillColor(colors.HexColor("#111111"))
    c.rect(0, PAGE_H - 54, PAGE_W, 54, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(M, PAGE_H - 31, "Shadowrun 3rd Edition Character Sheet")
    c.setFont("Helvetica", 7)
    c.drawRightString(PAGE_W - M, PAGE_H - 23, "Original fillable fan worksheet")
    c.drawRightString(PAGE_W - M, PAGE_H - 36, "For personal campaign use")

    y = PAGE_H - 79
    section(c, "Character Identity", M, y - 104, PAGE_W - 2 * M, 104)
    x = M + 8
    boxed_field(c, "character_name", "Character Name", x, y - 29, 185)
    boxed_field(c, "player", "Player", x + 195, y - 29, 115)
    boxed_field(c, "campaign", "Campaign", x + 320, y - 29, 190)
    boxed_field(c, "metatype", "Metatype", x, y - 60, 82)
    boxed_field(c, "archetype", "Archetype / Concept", x + 92, y - 60, 132)
    boxed_field(c, "sex", "Sex", x + 234, y - 60, 38)
    boxed_field(c, "age", "Age", x + 282, y - 60, 36)
    boxed_field(c, "height", "Height", x + 328, y - 60, 45)
    boxed_field(c, "weight", "Weight", x + 383, y - 60, 45)
    boxed_field(c, "street_name", "Street Name", x + 438, y - 60, 72)
    boxed_field(c, "description", "Description / Style", x, y - 91, 510)

    y2 = y - 124
    section(c, "Core Attributes", M, y2 - 160, 174, 160)
    small_grid(c, "attr", ["Body", "Quickness", "Strength", "Charisma", "Intelligence", "Willpower", "Essence", "Magic"], M + 10, y2 - 37, 54)
    small_grid(c, "derived", ["Reaction", "Initiative", "Combat Pool", "Karma Pool", "Spell Pool", "Task Pool"], M + 92, y2 - 37, 62)

    section(c, "Priorities / Build Notes", M + 184, y2 - 160, 174, 160)
    for i, item in enumerate(["Metatype", "Attributes", "Skills", "Resources", "Magic"]):
        yy = y2 - 36 - i * 21
        label(c, item, M + 195, yy + 3, 7, True)
        text_field(c, f"priority_{item.lower()}", M + 260, yy, 45, 12)
        text_field(c, f"priority_{item.lower()}_notes", M + 310, yy, 62, 12)
    boxed_field(c, "nuyen_start", "Starting Nuyen", M + 195, y2 - 145, 72)
    boxed_field(c, "karma_total", "Good Karma", M + 280, y2 - 145, 76)

    section(c, "Condition Monitors", M + 368, y2 - 160, 214, 160)
    condition_monitor(c, "physical", "Physical Damage", M + 380, y2 - 55)
    condition_monitor(c, "stun", "Stun Damage", M + 380, y2 - 101)
    boxed_field(c, "overflow", "Overflow", M + 380, y2 - 145, 42)
    boxed_field(c, "wounds_notes", "Wound / Modifier Notes", M + 434, y2 - 145, 128)

    y3 = y2 - 184
    section(c, "Active Skills", M, y3 - 206, 265, 206)
    line_table(c, "active_skill", ["Skill", "Rating", "Pool/Spec", "Notes"], 39, y3 - 32, [88, 38, 56, 70], 17)

    section(c, "Knowledge / Language Skills", M + 275, y3 - 206, 140, 206)
    line_table(c, "knowledge_skill", ["Skill", "Rating", "Notes"], M + 284, y3 - 32, [65, 28, 35], 17)

    section(c, "Contacts", M + 425, y3 - 206, 157, 206)
    line_table(c, "contact", ["Name", "Type", "Loyalty"], M + 434, y3 - 32, [66, 50, 28], 17)

    y4 = y3 - 230
    section(c, "Magic, Matrix, or Special Notes", M, y4 - 118, 552, 118)
    checkbox(c, "mundane", M + 10, y4 - 35, "Mundane")
    checkbox(c, "adept", M + 85, y4 - 35, "Adept")
    checkbox(c, "magician", M + 150, y4 - 35, "Magician")
    checkbox(c, "aspected", M + 235, y4 - 35, "Aspected")
    checkbox(c, "decker", M + 325, y4 - 35, "Decker")
    checkbox(c, "rigger", M + 398, y4 - 35, "Rigger")
    text_field(c, "magic_matrix_notes", M + 10, y4 - 103, 532, 55, 7, multiline=True)

    c.showPage()

    c.setFillColor(colors.HexColor("#111111"))
    c.rect(0, PAGE_H - 42, PAGE_W, 42, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(M, PAGE_H - 27, "Shadowrun 3E Character Sheet: Equipment and Advancement")
    c.setFont("Helvetica", 7)
    c.drawRightString(PAGE_W - M, PAGE_H - 24, "Page 2")

    y = PAGE_H - 65
    section(c, "Weapons", M, y - 158, 552, 158)
    line_table(c, "weapon", ["Weapon", "Conc.", "Damage", "Mode", "Ammo", "RC", "Reach", "Notes"], M + 8, y - 33, [104, 40, 58, 45, 45, 34, 40, 168], 17)

    y -= 180
    section(c, "Armor, Gear, and Lifestyle", M, y - 190, 270, 190)
    boxed_field(c, "armor", "Armor / Ballistic / Impact", M + 10, y - 36, 118)
    boxed_field(c, "lifestyle", "Lifestyle", M + 140, y - 36, 72)
    boxed_field(c, "monthly_cost", "Monthly Cost", M + 220, y - 36, 58)
    text_field(c, "gear_list", M + 10, y - 176, 250, 118, 7, multiline=True)

    section(c, "Cyberware / Bioware", M + 282, y - 190, 270, 190)
    line_table(c, "ware", ["Implant", "Rating", "Essence", "Notes"], M + 290, y - 33, [92, 40, 48, 72], 18)
    boxed_field(c, "essence_remaining", "Essence Remaining", M + 290, y - 176, 76)
    boxed_field(c, "bio_index", "Bio Index", M + 382, y - 176, 58)
    boxed_field(c, "cyber_notes", "Notes", M + 452, y - 176, 90)

    y -= 212
    section(c, "Vehicles / Drones", M, y - 138, 270, 138)
    line_table(c, "vehicle", ["Vehicle", "Handling", "Speed", "Notes"], M + 8, y - 33, [78, 50, 42, 92], 18)

    section(c, "Spells / Powers / Programs", M + 282, y - 138, 270, 138)
    line_table(c, "special_list", ["Name", "Rating", "Drain/Cost", "Notes"], M + 290, y - 33, [86, 40, 55, 72], 18)

    y -= 160
    section(c, "Advancement and Campaign Log", M, y - 128, 552, 128)
    boxed_field(c, "karma_earned", "Karma Earned", M + 10, y - 36, 66)
    boxed_field(c, "karma_spent", "Karma Spent", M + 90, y - 36, 66)
    boxed_field(c, "current_nuyen", "Current Nuyen", M + 170, y - 36, 80)
    boxed_field(c, "reputation", "Reputation / Heat", M + 265, y - 36, 100)
    boxed_field(c, "last_updated", "Last Updated", M + 382, y - 36, 90)
    text_field(c, "campaign_log", M + 10, y - 113, 532, 58, 7, multiline=True)

    c.setFillColor(colors.HexColor("#555555"))
    c.setFont("Helvetica", 6)
    c.drawString(M, 18, "This is an original, unofficial fan worksheet for use with Shadowrun 3rd Edition campaigns.")
    c.save()
    print(OUT)


if __name__ == "__main__":
    build()
